### PR TITLE
Introduce content selectability feature & fix content section linking

### PR DESCRIPTION
**Pull request by dinuand**
As a user would be kind of frustrating to have the permission to select content from a website.
This patch fixes the vulnerability, so the user is not allowed to do any text or image selection even in modals.

For the content section linking I added some padding between sections and now it works fine.

### CODE REVIEW

**Comment by dinuand** [comment]
The previous commits won't affect the main repo. If you take a look, the diff is only in the lines of code that take care of content selectability and content linking problem.

**Comment by dinuand** [comment]
The previous solution that I had for the content linking bug was adding a lot of padding between sections and it didn't look so nice even if it worked. However, now I found a better way to fix the problem using a border, negative margins, and background-clip. In addition, it seems that is supported by all browsers: Firefox 1.0+, Opera 10.5+, Safari 3+, Chrome.

**Comment by maria** [comment]
You are adding some history which is not necessary. Please recreate the pull request, cherry-pick the correct commits, on top of a new branch, which is created from rosedu/sites_template/master. You have access to the repo now, and you can push.

**Comment by dinuand** [comment]
Sorry, it seems I don't have access to this repo and I can't create new branches. Please, add it to the cdl team group. Thank's.

**Comment by maria** [comment]
Done.

**Pull request closed without merging**
