### PR TITLE
Fixes #4 Define plug-able structure

### LINKED ISSUE #4: Define site unique elements in one place
## Problem

The template has some moving parts, which will have to be
changed when one uses it to create a project site.

To be easy to determine and change those elements,
they should be defined in a single place and documented.
### Solution
- [ ] Define font, menu anchor colours in one place in the stylesheet
- [ ] Define each article type in a layout 
- [ ] Define data in `_data` directory
- [ ] #2

### PR DESCRIPTION
**Pull request by maria**
#4

### CODE REVIEW

**Comment by maria** [comment]
@mihaibivol you were interested about this. :)

**Comment by mihaibivol** [comment]
@marianitadn This meaning that each maintainer is in charge of manually updating their sites to use this feature?

**Comment by mihaibivol** [comment]
Probably some jade templates would also work

**Comment by maria** [comment]
we can do Jade templates for Python frameworks. I can make a script to do this, but in time. I'm waiting for feedback and then we can improve with different miscellaneous.

**Comment by dinuand** [comment]
Is much more flexible right now. I think you did it pretty well and it's enough for the moment, so we can use this as a starting point for the CDL website. 

However, just a remark. 
Right now, we are only having a general image for all our book entries. I think we want that each _book-item_ to have a specific image, so the elements in _books.yml_ should contain also a field named _image_. Then, we could use _item.image_ in _book-item.html_.
I can take care of that.

**Comment by maria** [comment]
I will finish it tonight. Thanks :-)

**Pull request merged**
